name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Testing on Node LTS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Lint 💅
        run: pnpm format:check

      - name: Test 🧪
        run: pnpm test:run
